### ISSUE TITLE
Motionblind Akku Prozent anzeige, sehr ungenau

### ISSUE THREAD

**Issue by biker1602** [VBen/ioBroker.motionblinds#149]
Hallo
Ich habe mal eine Bitte.
Ist es möglich, dass die Anzeige für die Akku-Prozentzahl nachgeregelt wird? In der App ist die Batterie schon gelb.
![grafik](https://user-images.githubusercontent.com/85706081/202228480-8713284f-994b-4beb-8b9d-3f349a007fa8.png)

Im Adapter werden aber immer noch 72,8 % Akkuleistung angezeigt. Auch wenn er ganz voll geladen ist, werden nie 100 % angezeigt

**Comment by VBen** [comment]
Ich habe gerade nochmal nachgeschaut, das ist in Wahrheit nicht die % Anzeige sondern die Spannung
Ich werde das ganze bei Gelegenheit anpassen
72,8% = 7,28V

**Comment by biker1602** [comment]
Vielen Dank

 

Von: VBen ***@***.***> 
Gesendet: Sonntag, 20. November 2022 17:29
An: VBen/ioBroker.motionblinds ***@***.***>
Cc: biker1602 ***@***.***>; Author ***@***.***>
Betreff: Re: [VBen/ioBroker.motionblinds] Motionblind Akku Prozent anzeige, sehr ungenau (Issue #149)

 

Ich habe gerade nochmal nachgeschaut, das ist in Wahrheit nicht die % Anzeige sondern die Spannung
Ich werde das ganze bei Gelegenheit anpassen
72,8% = 7,28V

**Comment by L-C-P** [comment]
[node-motionblinds] already contains the correct way for the percentage calculation.

**Comment by VBen** [comment]
the error should be fixed in v.0.3.0-beta.0
