### ISSUE TITLE
[BUG] Installation error

### ISSUE THREAD

**Issue by jan98211** [VBen/ioBroker.motionblinds#193]
Wie ich im Forum schon gelesen habe lässt sich die neue Version nicht installieren, als ich es trotzdem versucht habe kam beim 2.ten Mal eine längere Fehlermeldung, vielleicht hilft diese weiter.

`$ iobroker url https://github.com/VBen/ioBroker.motionblinds.git --host iobroker --debug
install VBen/ioBroker.motionblinds#a770033d2e27f049912f488c723b289669557b12
Installing VBen/ioBroker.motionblinds#a770033d2e27f049912f488c723b289669557b12... (System call)
npm error code 127
npm error git dep preparation failednpm error command /usr/bin/node /usr/lib/node_modules/npm/bin/npm-cli.js install --force --cache=/home/iobroker/.npm --prefer-offline=false --prefer-online=false --offline=false --no-progress --no-save --no-audit --include=dev --include=peer --include=optional --no-package-lock-only --no-dry-runnpm error npm warn using --force Recommended protections disabled.npm error npm warn deprecated inflight@1.0.6: This module is not supported, and leaks memory. Do not use it. Check out lru-cache if you want a good and tested way to coalesce async requests by a key value, which is much more comprehensive and powerful.npm error npm warn deprecated rimraf@3.0.2: Rimraf versions prior to v4 are no longer supportednpm error npm warn deprecated rimraf@3.0.2: Rimraf versions prior to v4 are no longer supportednpm error npm warn deprecated rimraf@3.0.2: Rimraf versions prior to v4 are no longer supportednpm error npm warn deprecated glob@7.2.3: Glob versions prior to v9 are no longer supportednpm error npm warn deprecated glob@7.2.3: Glob versions prior to v9 are no longer supportednpm error npm warn deprecated glob@7.2.3: Glob versions prior to v9 are no longer supportednpm error npm warn deprecated glob@7.2.3: Glob versions prior to v9 are no longer supportednpm error npm warn deprecated glob@8.1.0: Glob versions prior to v9 are no longer supportednpm error npm warn deprecated google-p12-pem@4.0.1: Package is no longer maintainednpm error npm warn deprecated sinon@15.2.0: 16.1.1npm error npm error code 127npm error npm error git dep preparation failednpm error npm error command /usr/bin/node /usr/lib/node_modules/npm/bin/npm-cli.js install --force --cache=/home/iobroker/.npm --prefer-offline=false --prefer-online=false --offline=false --no-progress --no-save --no-audit --include=dev --include=peer --include=optional --no-package-lock-only --no-dry-runnpm error npm error > core-js-pure@3.9.0 postinstallnpm error npm error > node -e "try{require('./postinstall')}catch(e){}"npm error npm errornpm error npm error Thank you for using core-js ( https://github.com/zloirock/core-js ) for polyfilling JavaScript standard library!npm error npm errornpm error npm error The project needs your help! Please consider supporting of core-js on Open Collective or Patreon: npm error npm error > https://opencollective.com/core-js npm error npm error > https://www.patreon.com/zloirock npm error npm errornpm error npm error Also, the author of core-js ( https://github.com/zloirock ) is looking for a good job -)npm error npm errornpm error npm errornpm error npm error > husky@5.1.1 postinstallnpm error npm error > npm run build && node lib/bin installnpm error npm errornpm error npm errornpm error npm error > husky@5.1.1 prebuildnpm error npm error > del-cli libnpm error npm error npm warn using --force Recommended protections disabled.npm error npm error npm warn ERESOLVE overriding peer dependencynpm error npm error npm warn While resolving: tsdx@0.14.1npm error npm error npm warn Found: peer @typescript-eslint/parser@"^4.0.0" from @typescript-eslint/eslint-plugin@4.15.2npm error npm error npm warn node_modules/tsdx/node_modules/@typescript-eslint/eslint-pluginnpm error npm error npm warnnpm error npm error npm warn Could not resolve dependency:npm error npm error npm warn peer @typescript-eslint/parser@"^4.0.0" from @typescript-eslint/eslint-plugin@4.15.2npm error npm error npm warn node_modules/tsdx/node_modules/@typescript-eslint/eslint-pluginnpm error npm error npm warn deprecated is-data-descriptor@0.1.4: Please upgrade to v0.1.5npm error npm error npm warn deprecated is-accessor-descriptor@0.1.6: Please upgrade to v0.1.7npm error npm error npm warn deprecated is-data-descriptor@0.1.4: Please upgrade to v0.1.5npm error npm error npm warn deprecated is-accessor-descriptor@0.1.6: Please upgrade to v0.1.7npm error npm error npm warn deprecated is-data-descriptor@0.1.4: Please upgrade to v0.1.5npm error npm error npm warn deprecated is-accessor-descriptor@0.1.6: Please upgrade to v0.1.7npm error npm error npm warn deprecated is-data-descriptor@1.0.0: Please upgrade to v1.0.1npm error npm error npm warn deprecated is-accessor-descriptor@1.0.0: Please upgrade to v1.0.1npm error npm error npm warn deprecated is-data-descriptor@0.1.4: Please upgrade to v0.1.5npm error npm error npm warn deprecated is-accessor-descriptor@0.1.6: Please upgrade to v0.1.7npm error npm error npm warn deprecated is-data-descriptor@0.1.4: Please upgrade to v0.1.5npm error npm error npm warn deprecated is-accessor-descriptor@0.1.6: Please upgrade to v0.1.7npm error npm error npm warn deprecated inflight@1.0.6: This module is not supported, and leaks memory. Do not use it. Check out lru-cache if you want a good and tested way to coalesce async requests by a key value, which is much more comprehensive and powerful.npm error npm error npm warn deprecated source-map-url@0.4.1: See https://github.com/lydell/source-map-url#deprecatednpm error npm error npm warn deprecated @babel/plugin-proposal-unicode-property-regex@7.12.13: This proposal has been merged to the ECMAScript standard and thus this plugin is no longer maintained. Please use @babel/plugin-transform-unicode-property-regex instead.npm error npm error npm warn deprecated @babel/plugin-proposal-private-methods@7.12.13: This proposal has been merged to the ECMAScript standard and thus this plugin is no longer maintained. Please use @babel/plugin-transform-private-methods instead.npm error npm error npm warn deprecated @babel/plugin-proposal-optional-catch-binding@7.12.13: This proposal has been merged to the ECMAScript standard and thus this plugin is no longer maintained. Please use @babel/plugin-transform-optional-catch-binding instead.npm error npm error npm warn deprecated @babel/plugin-proposal-numeric-separator@7.12.13: This proposal has been merged to the ECMAScript standard and thus this plugin is no longer maintained. Please use @babel/plugin-transform-numeric-separator instead.npm error npm error npm warn deprecated @babel/plugin-proposal-nullish-coalescing-operator@7.12.13: This proposal has been merged to the ECMAScript standard and thus this plugin is no longer maintained. Please use @babel/plugin-transform-nullish-coalescing-operator instead.npm error npm error npm warn deprecated @babel/plugin-proposal-logical-assignment-operators@7.12.13: This proposal has been merged to the ECMAScript standard and thus this plugin is no longer maintained. Please use @babel/plugin-transform-logical-assignment-operators instead.npm error npm error npm warn deprecated @babel/plugin-proposal-export-namespace-from@7.12.13: This proposal has been merged to the ECMAScript standard and thus this plugin is no longer maintained. Please use @babel/plugin-transform-export-namespace-from instead.npm error npm error npm warn deprecated @babel/plugin-proposal-dynamic-import@7.12.17: This proposal has been merged to the ECMAScript standard and thus this plugin is no longer maintained. Please use @babel/plugin-transform-dynamic-import instead.npm error npm error npm warn deprecated @babel/plugin-proposal-json-strings@7.12.13: This proposal has been merged to the ECMAScript standard and thus this plugin is no longer maintained. Please use @babel/plugin-transform-json-strings instead.npm error npm error npm warn deprecated @babel/plugin-proposal-class-properties@7.12.13: This proposal has been merged to the ECMAScript standard and thus this plugin is no longer maintained. Please use @babel/plugin-transform-class-properties instead.npm error npm error npm warn deprecated request-promise-native@1.0.9: request-promise-native has been deprecated because it extends the now deprecated request package, see https://github.com/request/request/issues/3142npm error npm error npm warn deprecated rimraf@2.6.3: Rimraf versions prior to v4 are no longer supportednpm error npm error npm warn deprecated @babel/plugin-proposal-async-generator-functions@7.12.13: This proposal has been merged to the ECMAScript standard and thus this plugin is no longer maintained. Please use @babel/plugin-transform-async-generator-functions instead.npm error npm error npm warn deprecated rollup-plugin-terser@5.3.1: This package has been deprecated and is no longer maintained. Please use @rollup/plugin-tersernpm error npm error npm warn deprecated urix@0.1.0: Please see https://github.com/lydell/urix#deprecatednpm error npm error npm warn deprecated source-map-resolve@0.6.0: See https://github.com/lydell/source-map-resolve#deprecatednpm error npm error npm warn deprecated har-validator@5.1.5: this library is no longer supportednpm error npm error npm warn deprecated @babel/plugin-proposal-object-rest-spread@7.12.13: This proposal has been merged to the ECMAScript standard and thus this plugin is no longer maintained. Please use @babel/plugin-transform-object-rest-spread instead.npm error npm error npm warn deprecated rimraf@3.0.2: Rimraf versions prior to v4 are no longer supportednpm error npm error npm warn deprecated @babel/plugin-proposal-optional-chaining@7.12.17: This proposal has been merged to the ECMAScript standard and thus this plugin is no longer maintained. Please use @babel/plugin-transform-optional-chaining instead.npm error npm error npm warn deprecated domexception@1.0.1: Use your platform's native DOMException insteadnpm error npm error npm warn deprecated abab@2.0.5: Use your platform's native atob() and btoa() methods insteadnpm error npm error npm warn deprecated resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecatednpm error npm error npm warn deprecated source-map-resolve@0.5.3: See https://github.com/lydell/source-map-resolve#deprecatednpm error npm error npm warn deprecated glob@7.1.6: Glob versions prior to v9 are no longer supported
npm error npm error npm warn deprecated w3c-hr-time@1.0.2: Use your platform's native performance.now() and performance.timeOrigin.npm error npm error npm warn deprecated sourcemap-codec@1.4.8: Please use @jridgewell/sourcemap-codec insteadnpm error npm error npm warn deprecated sane@4.1.0: some dependency vulnerabilities fixed, support for node < 10 dropped, and newer ECMAScript syntax/features addednpm error npm error npm warn deprecated babel-eslint@10.1.0: babel-eslint is now @babel/eslint-parser. This package will no longer receive updates.npm error npm error npm warn deprecated uuid@3.4.0: Please upgrade to version 7 or higher. Older versions may use Math.random() in certain circumstances, which is known to be problematic. See https://v8.dev/blog/math-random for details.npm error npm error npm warn deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142npm error npm error npm warn deprecated core-js-pure@3.9.0: core-js-pure@<3.23.3 is no longer maintained and not recommended for usage due to the number of issues. Because of the V8 engine whims, feature detection in old core-js versions could cause a slowdown up to 100x even if nothing is polyfilled. Some versions have web compatibility issues. Please, upgrade your dependencies to the actual version of core-js-pure.npm error npm error npm warn using --force Recommended protections disabled.npm error npm error sh: 1: del-cli: not foundnpm error npm error npm error code 127npm error npm error npm error path /home/iobroker/.npm/_cacache/tmp/git-cloneXXXXXXe3vRmY/node_modules/huskynpm error npm error npm error command failednpm error npm error npm error command sh -c npm run build && node lib/bin installnpm error npm error npm error A complete log of this run can be found in: /home/iobroker/.npm/_logs/2024-08-15T18_35_45_978Z-debug-0.lognpm error npm error A complete log of this run can be found in: /home/iobroker/.npm/_logs/2024-08-15T18_35_35_818Z-debug-0.lognpm error A complete log of this run can be found in: /home/iobroker/.npm/_logs/2024-08-15T18_35_21_597Z-debug-0.log
npm error code 127npm error git dep preparation failednpm error command /usr/bin/node /usr/lib/node_modules/npm/bin/npm-cli.js install --force --cache=/home/iobroker/.npm --prefer-offline=false --prefer-online=false --offline=false --no-progress --no-save --no-audit --include=dev --include=peer --include=optional --no-package-lock-only --no-dry-runnpm error npm warn using --force Recommended protections disabled.npm error npm warn deprecated inflight@1.0.6: This module is not supported, and leaks memory. Do not use it. Check out lru-cache if you want a good and tested way to coalesce async requests by a key value, which is much more comprehensive and powerful.npm error npm warn deprecated rimraf@3.0.2: Rimraf versions prior to v4 are no longer supportednpm error npm warn deprecated rimraf@3.0.2: Rimraf versions prior to v4 are no longer supportednpm error npm warn deprecated rimraf@3.0.2: Rimraf versions prior to v4 are no longer supportednpm error npm warn deprecated glob@7.2.3: Glob versions prior to v9 are no longer supportednpm error npm warn deprecated glob@7.2.3: Glob versions prior to v9 are no longer supportednpm error npm warn deprecated glob@7.2.3: Glob versions prior to v9 are no longer supportednpm error npm warn deprecated glob@7.2.3: Glob versions prior to v9 are no longer supportednpm error npm warn deprecated glob@8.1.0: Glob versions prior to v9 are no longer supportednpm error npm warn deprecated google-p12-pem@4.0.1: Package is no longer maintainednpm error npm warn deprecated sinon@15.2.0: 16.1.1npm error npm error code 127npm error npm error git dep preparation failednpm error npm error command /usr/bin/node /usr/lib/node_modules/npm/bin/npm-cli.js install --force --cache=/home/iobroker/.npm --prefer-offline=false --prefer-online=false --offline=false --no-progress --no-save --no-audit --include=dev --include=peer --include=optional --no-package-lock-only --no-dry-runnpm error npm error > core-js-pure@3.9.0 postinstallnpm error npm error > node -e "try{require('./postinstall')}catch(e){}"npm error npm errornpm error npm error Thank you for using core-js ( https://github.com/zloirock/core-js ) for polyfilling JavaScript standard library!npm error npm errornpm error npm error The project needs your help! Please consider supporting of core-js on Open Collective or Patreon: npm error npm error > https://opencollective.com/core-js npm error npm error > https://www.patreon.com/zloirock npm error npm errornpm error npm error Also, the author of core-js ( https://github.com/zloirock ) is looking for a good job -)npm error npm errornpm error npm errornpm error npm error > husky@5.1.1 postinstallnpm error npm error > npm run build && node lib/bin installnpm error npm errornpm error npm errornpm error npm error > husky@5.1.1 prebuildnpm error npm error > del-cli libnpm error npm error npm warn using --force Recommended protections disabled.npm error npm error npm warn ERESOLVE overriding peer dependencynpm error npm error npm warn While resolving: tsdx@0.14.1npm error npm error npm warn Found: peer @typescript-eslint/parser@"^4.0.0" from @typescript-eslint/eslint-plugin@4.15.2npm error npm error npm warn node_modules/tsdx/node_modules/@typescript-eslint/eslint-pluginnpm error npm error npm warnnpm error npm error npm warn Could not resolve dependency:npm error npm error npm warn peer @typescript-eslint/parser@"^4.0.0" from @typescript-eslint/eslint-plugin@4.15.2npm error npm error npm warn node_modules/tsdx/node_modules/@typescript-eslint/eslint-pluginnpm error npm error npm warn deprecated is-data-descriptor@0.1.4: Please upgrade to v0.1.5npm error npm error npm warn deprecated is-accessor-descriptor@0.1.6: Please upgrade to v0.1.7npm error npm error npm warn deprecated is-data-descriptor@0.1.4: Please upgrade to v0.1.5npm error npm error npm warn deprecated is-accessor-descriptor@0.1.6: Please upgrade to v0.1.7npm error npm error npm warn deprecated is-data-descriptor@0.1.4: Please upgrade to v0.1.5npm error npm error npm warn deprecated is-accessor-descriptor@0.1.6: Please upgrade to v0.1.7npm error npm error npm warn deprecated is-data-descriptor@1.0.0: Please upgrade to v1.0.1npm error npm error npm warn deprecated is-accessor-descriptor@1.0.0: Please upgrade to v1.0.1npm error npm error npm warn deprecated is-data-descriptor@0.1.4: Please upgrade to v0.1.5npm error npm error npm warn deprecated is-accessor-descriptor@0.1.6: Please upgrade to v0.1.7npm error npm error npm warn deprecated is-data-descriptor@0.1.4: Please upgrade to v0.1.5npm error npm error npm warn deprecated is-accessor-descriptor@0.1.6: Please upgrade to v0.1.7npm error npm error npm warn deprecated inflight@1.0.6: This module is not supported, and leaks memory. Do not use it. Check out lru-cache if you want a good and tested way to coalesce async requests by a key value, which is much more comprehensive and powerful.npm error npm error npm warn deprecated source-map-url@0.4.1: See https://github.com/lydell/source-map-url#deprecatednpm error npm error npm warn deprecated @babel/plugin-proposal-unicode-property-regex@7.12.13: This proposal has been merged to the ECMAScript standard and thus this plugin is no longer maintained. Please use @babel/plugin-transform-unicode-property-regex instead.npm error npm error npm warn deprecated @babel/plugin-proposal-private-methods@7.12.13: This proposal has been merged to the ECMAScript standard and thus this plugin is no longer maintained. Please use @babel/plugin-transform-private-methods instead.npm error npm error npm warn deprecated @babel/plugin-proposal-optional-catch-binding@7.12.13: This proposal has been merged to the ECMAScript standard and thus this plugin is no longer maintained. Please use @babel/plugin-transform-optional-catch-binding instead.npm error npm error npm warn deprecated @babel/plugin-proposal-numeric-separator@7.12.13: This proposal has been merged to the ECMAScript standard and thus this plugin is no longer maintained. Please use @babel/plugin-transform-numeric-separator instead.npm error npm error npm warn deprecated @babel/plugin-proposal-nullish-coalescing-operator@7.12.13: This proposal has been merged to the ECMAScript standard and thus this plugin is no longer maintained. Please use @babel/plugin-transform-nullish-coalescing-operator instead.npm error npm error npm warn deprecated @babel/plugin-proposal-logical-assignment-operators@7.12.13: This proposal has been merged to the ECMAScript standard and thus this plugin is no longer maintained. Please use @babel/plugin-transform-logical-assignment-operators instead.npm error npm error npm warn deprecated @babel/plugin-proposal-export-namespace-from@7.12.13: This proposal has been merged to the ECMAScript standard and thus this plugin is no longer maintained. Please use @babel/plugin-transform-export-namespace-from instead.npm error npm error npm warn deprecated @babel/plugin-proposal-dynamic-import@7.12.17: This proposal has been merged to the ECMAScript standard and thus this plugin is no longer maintained. Please use @babel/plugin-transform-dynamic-import instead.npm error npm error npm warn deprecated @babel/plugin-proposal-json-strings@7.12.13: This proposal has been merged to the ECMAScript standard and thus this plugin is no longer maintained. Please use @babel/plugin-transform-json-strings instead.npm error npm error npm warn deprecated @babel/plugin-proposal-class-properties@7.12.13: This proposal has been merged to the ECMAScript standard and thus this plugin is no longer maintained. Please use @babel/plugin-transform-class-properties instead.npm error npm error npm warn deprecated request-promise-native@1.0.9: request-promise-native has been deprecated because it extends the now deprecated request package, see https://github.com/request/request/issues/3142npm error npm error npm warn deprecated rimraf@2.6.3: Rimraf versions prior to v4 are no longer supportednpm error npm error npm warn deprecated @babel/plugin-proposal-async-generator-functions@7.12.13: This proposal has been merged to the ECMAScript standard and thus this plugin is no longer maintained. Please use @babel/plugin-transform-async-generator-functions instead.npm error npm error npm warn deprecated rollup-plugin-terser@5.3.1: This package has been deprecated and is no longer maintained. Please use @rollup/plugin-tersernpm error npm error npm warn deprecated urix@0.1.0: Please see https://github.com/lydell/urix#deprecatednpm error npm error npm warn deprecated source-map-resolve@0.6.0: See https://github.com/lydell/source-map-resolve#deprecatednpm error npm error npm warn deprecated har-validator@5.1.5: this library is no longer supportednpm error npm error npm warn deprecated @babel/plugin-proposal-object-rest-spread@7.12.13: This proposal has been merged to the ECMAScript standard and thus this plugin is no longer maintained. Please use @babel/plugin-transform-object-rest-spread instead.npm error npm error npm warn deprecated rimraf@3.0.2: Rimraf versions prior to v4 are no longer supportednpm error npm error npm warn deprecated @babel/plugin-proposal-optional-chaining@7.12.17: This proposal has been merged to the ECMAScript standard and thus this plugin is no longer maintained. Please use @babel/plugin-transform-optional-chaining instead.npm error npm error npm warn deprecated domexception@1.0.1: Use your platform's native DOMException insteadnpm error npm error npm warn deprecated abab@2.0.5: Use your platform's native atob() and btoa() methods insteadnpm error npm error npm warn deprecated resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecatednpm error npm error npm warn deprecated source-map-resolve@0.5.3: See https://github.com/lydell/source-map-resolve#deprecatednpm error npm error npm warn deprecated glob@7.1.6: Glob versions prior to v9 are no longer supportednpm error npm error npm warn deprecated w3c-hr-time@1.0.2: Use your platform's native performance.now() and performance.timeOrigin.npm error npm error npm warn deprecated sourcemap-codec@1.4.8: Please use @jridgewell/sourcemap-codec insteadnpm error npm error npm warn deprecated sane@4.1.0: some dependency vulnerabilities fixed, support for node < 10 dropped, and newer ECMAScript syntax/features addednpm error npm error npm warn deprecated babel-eslint@10.1.0: babel-eslint is now @babel/eslint-parser. This package will no longer receive updates.npm error npm error npm warn deprecated uuid@3.4.0: Please upgrade to version 7 or higher. Older versions may use Math.random() in certain circumstances, which is known to be problematic. See https://v8.dev/blog/math-random for details.npm error npm error npm warn deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142npm error npm error npm warn deprecated core-js-pure@3.9.0: core-js-pure@<3.23.3 is no longer maintained and not recommended for usage due to the number of issues. Because of the V8 engine whims, feature detection in old core-js versions could cause a slowdown up to 100x even if nothing is polyfilled. Some versions have web compatibility issues. Please, upgrade your dependencies to the actual version of core-js-pure.npm error npm error npm warn using --force Recommended protections disabled.npm error npm error sh: 1: del-cli: not foundnpm error npm error npm error code 127npm error npm error npm error path /home/iobroker/.npm/_cacache/tmp/git-cloneXXXXXXe3vRmY/node_modules/huskynpm error npm error npm error command failednpm error npm error npm error command sh -c npm run build && node lib/bin installnpm error npm error npm error A complete log of this run can be found in: /home/iobroker/.npm/_logs/2024-08-15T18_35_45_978Z-debug-0.lognpm error npm error A complete log of this run can be found in: /home/iobroker/.npm/_logs/2024-08-15T18_35_35_818Z-debug-0.lognpm error A complete log of this run can be found in: /home/iobroker/.npm/_logs/2024-08-15T18_35_21_597Z-debug-0.loghost.iobroker Cannot install VBen/ioBroker.motionblinds#a770033d2e27f049912f488c723b289669557b12: 127
ERROR: Process exited with code 25 `

Node.js: v20.16.0
NPM: 10.8.1

**Comment by VBen** [comment]
Danke für die Rückmeldung.
Inzwischen hab ich das problem gefunden, es braucht aber noch etwas bis es nachhaltig beseitigt ist.
Du kannst `iobroker url https://github.com/VBen/ioBroker.motionblinds/archive/refs/heads/develop.zip --host iobroker --debug ` ausprobieren, dann solltest du die letzte Entwickler Version bekommen, die kann sich aber ständig ändern und ist mit Vorsicht zu genießen.

Ich hoffe dass der Paketmaintainer vom [node-motionblinds](https://github.com/jhurliman/node-motionblinds) den bug noch fixed, damit das ganze auch unter windows funktioniert.

**Comment by biker1602** [comment]
Ich glaube da warte ich bis es stable ist. Ich möchte mir das jetzt nicht zerschießen.
