### ISSUE TITLE
Failed fetching list of MOTION Blinds

### ISSUE THREAD

**Issue by Kentrath** [VBen/ioBroker.motionblinds#85]
Hallo, ich habe zusätzliche Motoren gekauft und eingebaut. Leider kommt nun nur noch die oben genannte Fehlermeldung, wenn ich den Adapter neu starte. Auch wenn ich den debug Modus erhöhe gibt es keine sinnvollen Ausgaben.
Im Forum hat desmond-0 den Timeout von 3 auf 10 Sekunden erhöht und dann keine Probleme mehr gehabt. Wo kann ich denn den Timeout einstellen? Ich habe leider kein entsprechendes Feld gefunden.
Vielen Dank

**Comment by VBen** [comment]
Siehe  78796ffbbbaf982971949183b0bf6d1005b06346
Sollte jetzt funktionieren, würde mich freuen wenn du das testen könntest

**Comment by Kentrath** [comment]
Ich habe den Adapter deinstalliert und neu installiert. Die Timeout Option ist nun da. Leider bekomme ich die Fehlermeldung "Failed fetching list of MOTION Blinds" immer noch. Probiert habe ich Werte von 10, 20 und 30 Sekunden.
In der Zwischenzeit habe ich einfach den alexa2 Adapter benutzt, um die Rollos zu steuern. Dort funktioniert alles soweit einwandfrei. Schade ist es dennoch, dass Dein Adapter mit 5 Motoren wunderbar funktioniert hat und nach der deutlichen Erhöhung an Motoren nicht mehr.

**Comment by VBen** [comment]
@Kentrath kannst du das Debug Level auf das Maximum stellen und mir dien Log Output hier anhängen?
wenn das token im log auftaucht bitte durch einen Platzhalter ersetzten

**Comment by Kentrath** [comment]
motionblinds.0 | 2022-03-27 21:46:47.363 | debug | undefined
motionblinds.0 | 2022-03-27 21:46:47.362 | error | Failed fetching list of MOTION Blinds: {}
motionblinds.0 | 2022-03-27 21:46:17.257 | info | Fetching device list
motionblinds.0 | 2022-03-27 21:46:17.256 | info | using timeout:30
motionblinds.0 | 2022-03-27 21:46:17.255 | info | config token: xxxxxxxxxxx
motionblinds.0 | 2022-03-27 21:46:17.243 | info | starting. Version 0.2.0 in /opt/iobroker/node_modules/iobroker.motionblinds, node: v12.22.11, js-controller: 4.0.21
motionblinds.0 | 2022-03-27 21:46:17.150 | debug | States connected to redis: 127.0.0.1:9000
motionblinds.0 | 2022-03-27 21:46:17.138 | debug | States create User PubSub Client
motionblinds.0 | 2022-03-27 21:46:17.138 | debug | States create System PubSub Client
motionblinds.0 | 2022-03-27 21:46:17.132 | debug | Redis States: Use Redis connection: 127.0.0.1:9000
motionblinds.0 | 2022-03-27 21:46:17.120 | debug | Objects connected to redis: 127.0.0.1:9001
motionblinds.0 | 2022-03-27 21:46:17.118 | debug | Objects client initialize lua scripts
motionblinds.0 | 2022-03-27 21:46:17.101 | debug | Objects create User PubSub Client
motionblinds.0 | 2022-03-27 21:46:17.101 | debug | Objects create System PubSub Client
motionblinds.0 | 2022-03-27 21:46:17.100 | debug | Objects client ready ... initialize now
motionblinds.0 | 2022-03-27 21:46:17.086 | debug | Redis Objects: Use Redis connection: 127.0.0.1:9001

**Comment by robbsta** [comment]
Hatte den Adapter in einem Test-System auch am Laufen. (Siro-Mini-Bridge)
Leider funktionierte das Finden von Devices ab der Firmeware A1.0.1_B0.1.4 nicht mehr.
Nachdem ich mein altes Javascript rausgekramt habe und geschaut habe ob das damit noch funktioniert, habe ich festgestellt, dass der ReadDevice-Aufruf in der neuen FW jetzt auch den accessToken benötigt. Vielleicht ist das bei anderen Bridges auch das Problem.
Daher nehme ich an, dass eine Korrektur/Anpassung eher in der MotionBlind-Lib angepasst werden muss: https://github.com/jhurliman/node-motionblinds.
Alter Aufruf:
{ msgType: "ReadDevice", mac: deviceMac, deviceType: deviceType, msgID: messageId} 
Neuer Aufruf:
{ msgType: "ReadDevice", mac: deviceMac, deviceType: deviceType, AccessToken: accessToken, msgID: messageId}
