### ISSUE TITLE
ReadDevice fails

### ISSUE THREAD

**Issue by VBen** [VBen/ioBroker.motionblinds#87]
Probleme bei ReadDevice von der Bridge

Hatte den Adapter in einem Test-System auch am Laufen. (Siro-Mini-Bridge)
Leider funktionierte das Finden von Devices ab der Firmeware A1.0.1_B0.1.4 nicht mehr.
Nachdem ich mein altes Javascript rausgekramt habe und geschaut habe ob das damit noch funktioniert, habe ich festgestellt, dass der ReadDevice-Aufruf in der neuen FW jetzt auch den accessToken benötigt. Vielleicht ist das bei anderen Bridges auch das Problem.
Daher nehme ich an, dass eine Korrektur/Anpassung eher in der MotionBlind-Lib angepasst werden muss: https://github.com/jhurliman/node-motionblinds.
Alter Aufruf:
{ msgType: "ReadDevice", mac: deviceMac, deviceType: deviceType, msgID: messageId} 
Neuer Aufruf:
{ msgType: "ReadDevice", mac: deviceMac, deviceType: deviceType, AccessToken: accessToken, msgID: messageId}

_Originally posted by @robbsta in https://github.com/VBen/ioBroker.motionblinds/issues/85#issuecomment-1080371750_

**Comment by VBen** [comment]
@robbsta @Kentrath
Welche Firmware-Version läuft auf der Bridge?

**Comment by robbsta** [comment]
Bridge ist die SIRO Connect SI7005 mit Firmware A1.0.1_B0.1.4.

**Comment by VBen** [comment]
Ich habe bei mir eine MotionBlinds CM02 bridge  mit A1.0.4_B0.1.6, mit der geht es

**Comment by robbsta** [comment]
Dann scheint die Siro-Bridge wohl noch ne andere/ältere Firmware zu haben, mit der vorherigen (120.1.irgendwas) ging es auch.
Ohne AccessToken bekomme ich beim Abruf:
{"msgType":"ReadDevice","mac":"12345","deviceType":"02000001","msgID":"20220328181605613"}
die Anwort 
{'msgType':'ReadDeviceAck','mac':'12345','msgID':'20220328181556427','token':'xxx','actionResult':'AccessToken error'}
Heartbeat, Report, und WriteDevice funktionieren wie gewünscht.

Ist es möglich einen Fallback einzubauen wenn ReadDeviceAck einen 'actionResult':'AccessToken error' enthält, und dann den Request mit AccessToken zu wiederholen? Oder wird der AccessToken vielleicht sogar ignoriert wenn er auch beim read übergeben wird und nicht benötigt wird?

**Comment by robbsta** [comment]
> 
Auf jeden Fall schon mal Danke für die schnelle Rückmeldung.
Klar, werde dort auch ein Issue aufmachen.

Der [ioBroker.connector-local-control](https://github.com/ConnectorGit/ioBroker.connector-local-control) geht auch nicht mehr, da kann ich das auch noch berichten.
Da die API bei beiden Anbietern gleich ist, habe ich mich für diesen hier entschieden, da er deutlich stabiler läuft und auch gepflegt wird.

**Comment by Kentrath** [comment]
Ich bin unterwegs, habe aber gerade eine neue Firmware installiert. Die hat die Nummer: A1.0.5_B0.1.6
Ich berichte mal, wenn ich wieder zu Hause bin.

**Comment by Kentrath** [comment]
Der log ist der selbe...

**Comment by VBen** [comment]
@Kentrath 
Kannst du die Version aus dem develop Branch installieren?
Im iobroker Verzeichnis ` npm i git@github.com:VBen/ioBroker.motionblinds.git#develop`
Was hast du für ein Betriebssystem?
Ist die Firewall eventuell aktiv?
Wenn der Adapter läuft lauscht er grundsätzlich nach Heartbeat messages(auch wenn info.connection 'false' ist), tauchen die im log auf?

**Comment by Kentrath** [comment]
Ich habe eine Debian VM auf einem Proxmox System. Anfangs hat ja alles funktioniert, als ich testweise nur 2 Motoren installiert hatte. Daher schließe ich Firewall-Probleme eigentlich aus. Erst als das System durch die zusätzlichen Motoren komplexer wurde fingen die Probleme an...
Leiser lässt sich das develop Paket nicht installieren. Auf Deinen Befehl hin bekomme ich folgende Fehlermeldung:

root@IoBroker:/opt/iobroker# npm i git@github.com:VBen/ioBroker.motionblinds.git#develop
npm ERR! code ENOLOCAL
npm ERR! Could not install from "github.com:VBen/ioBroker.motionblinds.git#develop" as it does not contain a package.json file.

**Comment by Kentrath** [comment]
Hier noch der ausführliche log vom Installationsversuch:

0 info it worked if it ends with ok
1 verbose cli [
1 verbose cli   '/usr/bin/node',
1 verbose cli   '/usr/bin/npm',
1 verbose cli   'i',
1 verbose cli   'git@github.com:VBen/ioBroker.motionblinds.git#develop'
1 verbose cli ]
2 info using npm@6.14.16
3 info using node@v12.22.11
4 verbose npm-session ad66ce19601c1206
5 silly install loadCurrentTree
6 silly install readLocalPackageData
7 silly fetchPackageMetaData error for git@file:github.com:VBen/ioBroker.motionblinds.git#develop Could not install from "github.com:VBen/ioBroker.motionblinds.git#develop" as it does not contain a package.json file.
8 timing stage:rollbackFailedOptional Completed in 0ms
9 timing stage:runTopLevelLifecycles Completed in 3732ms
10 verbose stack Error: ENOENT: no such file or directory, open '/opt/iobroker/github.com:VBen/ioBroker.motionblinds.git#develop/package.json'
11 verbose cwd /opt/iobroker
12 verbose Linux 5.10.0-12-amd64
13 verbose argv "/usr/bin/node" "/usr/bin/npm" "i" "git@github.com:VBen/ioBroker.motionblinds.git#develop"
14 verbose node v12.22.11
15 verbose npm  v6.14.16
16 error code ENOLOCAL
17 error Could not install from "github.com:VBen/ioBroker.motionblinds.git#develop" as it does not contain a package.json file.
18 verbose exit [ 1, true ]

**Comment by Kentrath** [comment]
motionblinds.0 | 2022-03-29 10:02:58.294 | debug | heartbeat timed out
motionblinds.0 | 2022-03-29 10:01:43.294 | info | heartbeat missing for more then 150 seconds, pleas check yor network connection
motionblinds.0 | 2022-03-29 10:01:43.294 | debug | heartbeat timed out
motionblinds.0 | 2022-03-29 10:00:28.293 | debug | heartbeat timed out

**Comment by VBen** [comment]
> motionblinds.0 | 2022-03-29 10:01:43.294 | info | heartbeat missing for more then 150 seconds, pleas check yor network connection

@Kentrath Das sieht mir stark nach einem Netzwerk Probelm aus. Es kommen keine Multicast Messages durch.
hast du eventuell einen anderen rechner(raspberry) mit dem man das testen kann?
theoretisch läuft es auch unter windows, wobei ich hier noch einiges tetsen muss

**Comment by Kentrath** [comment]
Einen Pi habe ich nicht, aber natürlich einen Windows Laptop. Was mich jedoch wundert ist, dass es anfangs geklappt hat. Ich habe am System bewusst nichts geändert, nur zusätzliche Motoren installiert. Da das einstellen der 0 % und 100 % Werte recht lästig ist will ich auch ungern die Konfiguration resetten, um dann einen Versuch mit  nur 2 Motoren zu starten...
An welchen Stellen könnten denn Firewalls eingreifen und was müsste ich gegebenenfalls freigeben? In der Fritzbox habe ich die Ports 32100 und 32101 für die VM frei gegeben. Auf der VM ist ufw installiert, aber nicht aktiv.

**Comment by Kentrath** [comment]
Ich habe es jetzt einfach noch einmal versucht, da ich vor kurzem auf die Firmware: A1.0.7_B0.1.6 geupdatet hatte. Nun geht es fast wieder, allerdings fehlt von den 16 Motoren einer? Habt Ihr eine Idee, woran das liegen könnte? Vielen Dank

**Comment by Kentrath** [comment]
Hat sich erledigt :-)
Der fehlende Motor ist mittlerweile aufgetaucht.
@VBen Das Issue kann geschlossen werden.
