### ISSUE TITLE
[BUG] Bridge appears as blind

### ISSUE THREAD

**Issue by biker1602** [VBen/ioBroker.motionblinds#89]
[](https://user-images.githubusercontent.com/85706081/160566146-11c0783b-ddd8-44c4-8b14-4c9f399fbc2c.png)Nach Neuinstallation zwei Rollos drin, obwohl nur eins installiert ist.
grafik

gehabt habe ich den
motionblinds.0.a4cf12fe46910004

und der ist dazu gekommen
motionblinds.0.a4cf12fe4691 mit weniger Daten.
Was hat das zu bedeuten?

Adapterversion 0.1.0
JS Controller version 5.2.21
[Node.js: v14.17.0](https://github.com/VBen/ioBroker.motionblinds/issues/89)
Plattform: linux
RAM: 3.7 GB
Node.js: v14.17.0
NPM: 6.14.13

**Comment by biker1602** [comment]
Nach Neuinstallation zwei Rollos drin, obwohl nur eins installiert ist.
![grafik](https://user-images.githubusercontent.com/85706081/160566146-11c0783b-ddd8-44c4-8b14-4c9f399fbc2c.png)

gehabt habe ich den
motionblinds.0.a4cf12fe46910004

und der ist dazu gekommen
motionblinds.0.a4cf12fe4691 mit weniger Daten.
Was hat das zu bedeuten?


 Adapterversion 0.1.0
JS Controller version 5.2.21
[Node.js: v14.17.0]()
    Plattform: linux
    RAM: 3.7 GB
    Node.js: v14.17.0
    NPM: 6.14.13

**Comment by VBen** [comment]
fixed with e08d22c3f716b98326939c8002c076e9ca79ac53
